name: GitHub Actions Demo
run-name: build bombardier
on: [push]
jobs:
  build bombardier:
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: build it
        run: docker info
