name: GitHub Actions Demo
run-name: build bombardier
on: [push]
jobs:
  build-bombardier:
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build it
        run: docker build .
