name: GitHub Actions Demo
run-name: build bombardier
on: [push]
jobs:
  build-bombardier:
    #runs-on: self-hosted 
    #runs-on: ubuntu-22.04
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 #     - name: build it
 #       run: docker build .
      - name: wait-for-it
        run: sleep 61
      - name: done
        run: echo "Times up"
 
